sudo: false
language: c

addons:
  apt:
    packages:
    - pandoc

script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh -g 1.13.3 | bash

branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
