deploy:
  provider: script
  script: 
  - source <(curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh)
  on:
    branches:
      only:
        - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
