name: CI

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_OAUTH }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Replace toc-versions
        uses: Numynum/ToCVersions@master
        with:
          args: Plugins/*/*.toc *.toc

      - name: Create Retail Package
        uses: BigWigsMods/packager@master

      - name: Create TBC Package
        uses: BigWigsMods/packager@master
        with:
          args: -g bc

      - name: Create Classic Package
        uses: BigWigsMods/packager@master
        with:
          args: -g classic
